### ISSUE TITLE
may i use standart probe with div 1:10, 1:100?

### ISSUE THREAD

**Issue by ghost** [martinloren/HScope#24]
Hello martinloren
big thanks for this project :)

im beginner and have some small questions

in Materials for HS101 PRO  i see - Voltage Ranges: ±15V, ±7.5V, ±3.25V, ±1.5V, **±470V**
how ±470V is works?, it need additional divider or i can connect this big voltage to HS101 PRO input, it is not dangerous?

i have standart oscilloscipe probe with selectable division 1:1 and 1:10, and another high voltage probe 1:100 up for 1500 volts, may i use it with HS101 PRO?

thank you

**Comment by martinloren** [comment]
Hi Neodim, sorry for late reply. 470 is not V, it should be mV. Then on top of these ranges you can apply a x10 or x20 or whatever other probe like in standard oscilloscopes. x100 will be dangerous as any other USB oscilloscope since the most of them are not insulated so the GND of the probe is the same as the GND of the oscilloscope and the same as the GND of the phone.

If you have an insulated x100 probe better, or you may try also the HS101 PRO Bluetooth so whatever happen it will stay in an insulated box you can build. Your phone will communicate just via Bluetooth.

Feel free to join the Telegram group for further discussions at https://t.me/hscope
